name: Deploy to VPS using SSH Key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /opt/final-devops-assignment
            git pull origin main
            echo "--> Deploying Server API..."
            cd server
            npm install
            pm2 restart webshop-api
            echo "--> Deploying Client..."
            cd ../
            sudo cp -r client/* /var/www/thanhquang.website/
            echo "--> Deployment successful!"
