name: Deploy to VPS using Password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Đi đến thư mục dự án trên VPS
            cd /opt/final-devops-assignment

            # Kéo code mới nhất từ GitHub
            git pull origin main

            # Triển khai Server API
            echo "--> Deploying Server API..."
            cd server
            npm install
            pm2 restart webshop-api

            # Triển khai Client
            echo "--> Deploying Client..."
            cd ../
            sudo cp -r client/* /var/www/thanhquang.website/

            echo "--> Deployment successful!"
